name: Docker CI/CD Pipeline

on: [push, pull_request]

jobs:
  security-scan: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Secure Hadolint (Docker Linter)
        uses: tmknom/secure-hadolint-action@v0.4.2
        with:
          failure-threshold: warning
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'          
          scan-ref: '.'             
          format: 'table'          
          exit-code: '1'          
          severity: 'CRITICAL,HIGH'
